-- VERIFICACIÓN DE USUARIO
SHOW USER;

-- ELIMINACIÓN DE TABLAS
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRADOR CASCADE CONSTRAINTS;
DROP TABLE HABITACION CASCADE CONSTRAINTS;
DROP TABLE RESERVA CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE NOTIFICACION CASCADE CONSTRAINTS;
DROP TABLE REPORTE CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;

-- CREACIÓN DE TABLAS
CREATE TABLE CLIENTE (
    id_cliente NUMBER(7) NOT NULL,
    nombre_cliente VARCHAR2(50) NOT NULL,
    apellido_cliente VARCHAR2(50) NOT NULL,
    email_cliente VARCHAR2(50) UNIQUE NOT NULL,
    telefono_cliente VARCHAR2(15),
    password_cliente VARCHAR2(100) NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (id_cliente)
);

CREATE TABLE ADMINISTRADOR (
    id_admin NUMBER(7) NOT NULL,
    nombre_admin VARCHAR2(50) NOT NULL,
    email_admin VARCHAR2(50) UNIQUE NOT NULL,
    password_admin VARCHAR2(100) NOT NULL,
    CONSTRAINT ADMINISTRADOR_PK PRIMARY KEY (id_admin)
);

CREATE TABLE HABITACION (
    id_habitacion NUMBER(6) NOT NULL,
    numero_habitacion VARCHAR2(10) NOT NULL,
    tipo VARCHAR2(20) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    capacidad NUMBER(2) DEFAULT 1,
    disponible CHAR(1) DEFAULT 'S',
    CONSTRAINT HABITACION_PK PRIMARY KEY (id_habitacion),
    CONSTRAINT chk_capacidad CHECK (capacidad >= 1),
    CONSTRAINT chk_disponible CHECK (disponible IN ('S','N'))
);

CREATE TABLE RESERVA (
    id_reserva NUMBER(8) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Pendiente',
    id_cliente NUMBER(7) NOT NULL,
    id_habitacion NUMBER(6) NOT NULL,
    CONSTRAINT RESERVA_PK PRIMARY KEY (id_reserva),
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente),
    CONSTRAINT fk_reserva_habitacion FOREIGN KEY (id_habitacion) REFERENCES HABITACION (id_habitacion),
    CONSTRAINT chk_fechas CHECK (fecha_fin > fecha_inicio)
);

CREATE TABLE PAGO (
    id_pago NUMBER(8) NOT NULL,
    monto NUMBER(10,2) NOT NULL,
    fecha_pago DATE DEFAULT SYSDATE,
    metodo_pago VARCHAR2(20) NOT NULL,
    id_reserva NUMBER(8) NOT NULL,
    CONSTRAINT PAGO_PK PRIMARY KEY (id_pago),
    CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva) REFERENCES RESERVA (id_reserva)
);

CREATE TABLE NOTIFICACION (
    id_notificacion NUMBER(8) NOT NULL,
    mensaje VARCHAR2(200) NOT NULL,
    fecha_envio DATE DEFAULT SYSDATE,
    id_cliente NUMBER(7) NOT NULL,
    CONSTRAINT NOTIFICACION_PK PRIMARY KEY (id_notificacion),
    CONSTRAINT fk_notif_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTE (id_cliente)
);

CREATE TABLE REPORTE (
    id_reporte NUMBER(6) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    fecha DATE DEFAULT SYSDATE,
    contenido VARCHAR2(500),
    id_admin NUMBER(7) NOT NULL,
    CONSTRAINT REPORTE_PK PRIMARY KEY (id_reporte),
    CONSTRAINT fk_reporte_admin FOREIGN KEY (id_admin) REFERENCES ADMINISTRADOR (id_admin)
);

CREATE TABLE SERVICIO (
    id_servicio NUMBER(6) NOT NULL,
    nombre_servicio VARCHAR2(50) NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (id_servicio)
);

-- INSERTS DE PRUEBA PARA LAS TABLAS
INSERT INTO CLIENTE VALUES (1, 'Juan', 'Pérez', 'juan.perez@mail.com', '912345678', '12345');
INSERT INTO CLIENTE VALUES (2, 'María', 'López', 'maria.lopez@mail.com', '976543210', '54321');

INSERT INTO ADMINISTRADOR VALUES (1, 'Carlos Ruiz', 'carlos.admin@mail.com', 'admin123');

INSERT INTO HABITACION VALUES (101, '101', 'Single', 35000, 1, 'S');
INSERT INTO HABITACION VALUES (102, '102', 'Doble', 50000, 2, 'S');
INSERT INTO HABITACION VALUES (201, '201', 'Suite', 90000, 4, 'N');

INSERT INTO RESERVA VALUES (1, TO_DATE('2024-09-10','YYYY-MM-DD'), TO_DATE('2024-09-15','YYYY-MM-DD'), 'Confirmada', 1, 101);
INSERT INTO RESERVA VALUES (2, TO_DATE('2024-09-12','YYYY-MM-DD'), TO_DATE('2024-09-14','YYYY-MM-DD'), 'Pendiente', 2, 102);

INSERT INTO PAGO VALUES (1, 35000, SYSDATE, 'Tarjeta Crédito', 1);

INSERT INTO NOTIFICACION VALUES (1, 'Su reserva ha sido confirmada', SYSDATE, 1);

INSERT INTO REPORTE VALUES (1, 'Ocupación Mensual', SYSDATE, 'Reporte de Septiembre', 1);

INSERT INTO SERVICIO VALUES (1, 'Spa', 20000);
INSERT INTO SERVICIO VALUES (2, 'Transporte Aeropuerto', 15000);

-- CONSULTAS A CADA TABLA PARA VISUALIZAR LA INFORMACION
SELECT * FROM CLIENTE;
SELECT * FROM ADMINISTRADOR;
SELECT * FROM HABITACION;
SELECT * FROM RESERVA;
SELECT * FROM PAGO;
SELECT * FROM NOTIFICACION;
SELECT * FROM REPORTE;
SELECT * FROM SERVICIO;